name: Build

on: [push, pull_request]

jobs:

  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Ubuntu
        run: |
          ./configure 
          make 
          make check
          
  MacOSX:
    runs-on: macosx-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build MacOSX
        run: |
          ./configure 
          make 
          make check        
    
  Windows-64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Windows 64 bit
        run:
          cd Projects\VC2019
          devenv lcms2.sln /Rebuild "Release|x64" /Project testbed
          cd ..\..\testbed
          testbed.exe

  Windows-64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Windows 32 bit
        run:
          cd Projects\VC2019
          devenv lcms2.sln /Rebuild "Release|Win32" /Project testbed
          cd ..\..\testbed
          testbed.exe

  Ubuntu-meson:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt-get -y install build-essential python3-pip ninja-build
          pip install meson==0.59.2

      - name: Build Ubuntu
        run: |
          meson setup build
          meson compile -C build
          meson test -C build

  VisualStudio-meson:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          pip install meson==0.59.2

      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build Windows
        run: |
          meson setup build
          meson compile -C build
          meson test -C build
